module.exports = {
    content: [
        "./src/**/*.{html,ts,scss}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: 'var(--color-primary)',
                    hover: 'var(--color-primary-hover)',
                    light: 'var(--color-primary-light)',
                    on: 'var(--color-on-primary)',
                },
                secondary: {
                    DEFAULT: 'var(--color-secondary)',
                    hover: 'var(--color-secondary-hover)',
                    light: 'var(--color-secondary-light)',
                },
                accent: {
                    DEFAULT: 'var(--color-accent)',
                    hover: 'var(--color-accent-hover)',
                    light: 'var(--color-accent-light)',
                },
                destructive: {
                    DEFAULT: 'var(--color-destructive)',
                    hover: 'var(--color-destructive-hover)',
                    light: 'var(--color-destructive-light)',
                },
                warning: {
                    DEFAULT: 'var(--color-warning)',
                    hover: 'var(--color-warning-hover)',
                    light: 'var(--color-warning-light)',
                },
                info: {
                    DEFAULT: 'var(--color-info)',
                    hover: 'var(--color-info-hover)',
                    light: 'var(--color-info-light)',
                },
                success: {
                    DEFAULT: 'var(--color-success)',
                    hover: 'var(--color-success-hover)',
                    light: 'var(--color-success-light)',
                },
                background: {
                    DEFAULT: 'var(--color-background)',
                    hover: 'var(--color-background-hover)',
                    active: 'var(--color-background-active)',
                },
                foreground: {
                    DEFAULT: 'var(--color-foreground)',
                    secondary: 'var(--color-foreground-secondary)',
                    tertiary: 'var(--color-foreground-tertiary)',
                    disabled: 'var(--color-foreground-disabled)',
                },
                muted: {
                    DEFAULT: 'var(--color-muted)',
                    hover: 'var(--color-muted-hover)',
                },
                border: {
                    DEFAULT: 'var(--color-border)',
                    light: 'var(--color-border-light)',
                    dark: 'var(--color-border-dark)',
                },
                surface: {
                    DEFAULT: 'var(--color-surface)',
                    hover: 'var(--color-surface-hover)',
                    active: 'var(--color-surface-active)',
                },
                overlay: {
                    DEFAULT: 'var(--color-overlay)',
                    light: 'var(--color-overlay-light)',
                },
                ring: 'var(--color-ring)',
            },
            fontFamily: {
                heading: ['var(--font-family-heading)', 'sans-serif'],
                body: ['var(--font-family-body)', 'sans-serif'],
                mono: ['var(--font-family-mono)', 'monospace'],
            },
            fontSize: {
                xs: 'var(--font-size-xs)',
                sm: 'var(--font-size-sm)',
                base: 'var(--font-size-base)',
                lg: 'var(--font-size-lg)',
                xl: 'var(--font-size-xl)',
                '2xl': 'var(--font-size-2xl)',
                '3xl': 'var(--font-size-3xl)',
                '4xl': 'var(--font-size-4xl)',
                '5xl': 'var(--font-size-5xl)',
            },
            fontWeight: {
                light: 'var(--font-weight-light)',
                normal: 'var(--font-weight-normal)',
                medium: 'var(--font-weight-medium)',
                semibold: 'var(--font-weight-semibold)',
                bold: 'var(--font-weight-bold)',
            },
            lineHeight: {
                tight: 'var(--line-height-tight)',
                snug: 'var(--line-height-snug)',
                normal: 'var(--line-height-normal)',
                relaxed: 'var(--line-height-relaxed)',
                loose: 'var(--line-height-loose)',
            },
            letterSpacing: {
                tight: 'var(--letter-spacing-tight)',
                normal: 'var(--letter-spacing-normal)',
                wide: 'var(--letter-spacing-wide)',
            },
            spacing: {
                0: 'var(--spacing-0)',
                1: 'var(--spacing-1)',
                2: 'var(--spacing-2)',
                3: 'var(--spacing-3)',
                4: 'var(--spacing-4)',
                5: 'var(--spacing-5)',
                6: 'var(--spacing-6)',
                8: 'var(--spacing-8)',
                10: 'var(--spacing-10)',
                12: 'var(--spacing-12)',
                16: 'var(--spacing-16)',
                20: 'var(--spacing-20)',
                24: 'var(--spacing-24)',
            },
            borderRadius: {
                xs: 'var(--radius-xs)',
                sm: 'var(--radius-sm)',
                md: 'var(--radius-md)',
                lg: 'var(--radius-lg)',
                xl: 'var(--radius-xl)',
                '2xl': 'var(--radius-2xl)',
                full: 'var(--radius-full)',
            },
            boxShadow: {
                xs: 'var(--shadow-xs)',
                sm: 'var(--shadow-sm)',
                md: 'var(--shadow-md)',
                lg: 'var(--shadow-lg)',
                xl: 'var(--shadow-xl)',
                '2xl': 'var(--shadow-2xl)',
            },
            transitionDuration: {
                fast: 'var(--transition-fast)',
                base: 'var(--transition-base)',
                slow: 'var(--transition-slow)',
            },
            transitionTimingFunction: {
                'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
            },
            zIndex: {
                dropdown: 'var(--z-index-dropdown)',
                sticky: 'var(--z-index-sticky)',
                fixed: 'var(--z-index-fixed)',
                'modal-backdrop': 'var(--z-index-modal-backdrop)',
                modal: 'var(--z-index-modal)',
                popover: 'var(--z-index-popover)',
                tooltip: 'var(--z-index-tooltip)',
            },
        },
    },
    plugins: [],
};